# Configuração do Dependabot para automação de dependências
# Gerenciado pelo RepoGuardian AI 🤖

version: 2
updates:
  # Dependências npm/pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    
    # Configurações de versionamento
    versioning-strategy: increase
    
    # Prefixos para commits
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    
    # Labels para PRs
    labels:
      - "dependencies"
      - "automated"
      - "maintenance"
    
    # Reviewers automáticos
    reviewers:
      - "felixskmarcio"
    
    # Assignees
    assignees:
      - "felixskmarcio"
    
    # Configurações de merge
    target-branch: "develop"
    
    # Ignorar certas dependências
    ignore:
      # Ignorar atualizações major do React (requer revisão manual)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      
      # Ignorar atualizações major do TypeScript (requer revisão manual)
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      
      # Ignorar atualizações major do Vite (requer revisão manual)
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      
      # Ignorar atualizações major do ESLint (requer revisão manual)
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
    
    # Agrupar atualizações relacionadas
    groups:
      # Grupo para dependências do React
      react:
        patterns:
          - "react*"
          - "@types/react*"
        
      # Grupo para ferramentas de build
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "rollup*"
          - "esbuild*"
        
      # Grupo para ferramentas de linting
      linting:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "prettier*"
        
      # Grupo para ferramentas de teste
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "jsdom*"
          - "@testing-library/*"
        
      # Grupo para dependências do Supabase
      supabase:
        patterns:
          - "@supabase/*"
          - "supabase*"
        
      # Grupo para dependências de UI
      ui:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "class-variance-authority"
          - "clsx"
          - "tailwind*"
        
      # Grupo para dependências de tipos
      types:
        patterns:
          - "@types/*"
    
    # Configurações de rebase
    rebase-strategy: "auto"
    
    # Configurações de milestone
    milestone: 1

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    
    # Prefixos para commits
    commit-message:
      prefix: "ci"
      include: "scope"
    
    # Labels para PRs
    labels:
      - "github-actions"
      - "automated"
      - "ci/cd"
    
    # Reviewers automáticos
    reviewers:
      - "felixskmarcio"
    
    # Assignees
    assignees:
      - "felixskmarcio"
    
    # Configurações de merge
    target-branch: "develop"
    
    # Agrupar atualizações de actions
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker (se houver Dockerfile no futuro)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    
    # Prefixos para commits
    commit-message:
      prefix: "docker"
      include: "scope"
    
    # Labels para PRs
    labels:
      - "docker"
      - "automated"
      - "infrastructure"
    
    # Reviewers automáticos
    reviewers:
      - "felixskmarcio"
    
    # Assignees
    assignees:
      - "felixskmarcio"
    
    # Configurações de merge
    target-branch: "develop"