# Configuração de Labels do Repositório
# Gerenciado pelo RepoGuardian AI 🤖
# Este arquivo define todas as labels usadas no repositório para categorização de Issues e PRs

# === TIPOS DE ISSUE/PR ===
- name: "bug"
  color: "d73a4a"
  description: "Algo não está funcionando corretamente"
  
- name: "feature"
  color: "0075ca"
  description: "Nova funcionalidade ou melhoria"
  
- name: "enhancement"
  color: "a2eeef"
  description: "Melhoria em funcionalidade existente"
  
- name: "documentation"
  color: "0052cc"
  description: "Melhorias ou adições na documentação"
  
- name: "refactor"
  color: "fbca04"
  description: "Refatoração de código sem mudança de funcionalidade"
  
- name: "performance"
  color: "ff9500"
  description: "Melhorias de performance"
  
- name: "security"
  color: "b60205"
  description: "Questões relacionadas à segurança"
  
- name: "accessibility"
  color: "7057ff"
  description: "Melhorias de acessibilidade"
  
- name: "ui/ux"
  color: "e99695"
  description: "Melhorias na interface do usuário"
  
- name: "api"
  color: "0e8a16"
  description: "Mudanças relacionadas à API"
  
- name: "database"
  color: "006b75"
  description: "Mudanças relacionadas ao banco de dados"
  
- name: "testing"
  color: "f9d0c4"
  description: "Adição ou correção de testes"

# === PRIORIDADES ===
- name: "priority:critical"
  color: "b60205"
  description: "🔥 Crítico - Precisa ser resolvido imediatamente"
  
- name: "priority:high"
  color: "d93f0b"
  description: "🔴 Alta prioridade"
  
- name: "priority:medium"
  color: "fbca04"
  description: "🟡 Prioridade média"
  
- name: "priority:low"
  color: "0e8a16"
  description: "🟢 Baixa prioridade"
  
- name: "priority:backlog"
  color: "ededed"
  description: "📋 No backlog para futuras versões"

# === STATUS ===
- name: "status:needs-triage"
  color: "ededed"
  description: "🔍 Precisa ser analisado pela equipe"
  
- name: "status:needs-info"
  color: "d876e3"
  description: "❓ Aguardando mais informações"
  
- name: "status:needs-review"
  color: "fbca04"
  description: "👀 Aguardando revisão"
  
- name: "status:in-progress"
  color: "0075ca"
  description: "🚧 Em desenvolvimento"
  
- name: "status:blocked"
  color: "b60205"
  description: "🚫 Bloqueado por dependência externa"
  
- name: "status:ready-for-test"
  color: "0e8a16"
  description: "✅ Pronto para teste"
  
- name: "status:done"
  color: "0e8a16"
  description: "✅ Concluído"
  
- name: "status:wontfix"
  color: "ffffff"
  description: "❌ Não será corrigido"
  
- name: "status:duplicate"
  color: "cfd3d7"
  description: "👥 Duplicata de outra issue"

# === DIFICULDADE ===
- name: "difficulty:beginner"
  color: "7057ff"
  description: "🌱 Bom para iniciantes"
  
- name: "difficulty:intermediate"
  color: "0075ca"
  description: "🔧 Nível intermediário"
  
- name: "difficulty:advanced"
  color: "d93f0b"
  description: "🎯 Nível avançado"
  
- name: "difficulty:expert"
  color: "b60205"
  description: "🚀 Apenas para experts"

# === ÁREAS DO PROJETO ===
- name: "area:frontend"
  color: "1d76db"
  description: "🎨 Interface do usuário (React/TypeScript)"
  
- name: "area:backend"
  color: "0e8a16"
  description: "⚙️ Lógica do servidor (Supabase)"
  
- name: "area:database"
  color: "006b75"
  description: "🗄️ Estrutura e queries do banco"
  
- name: "area:auth"
  color: "5319e7"
  description: "🔐 Autenticação e autorização"
  
- name: "area:tasks"
  color: "0075ca"
  description: "📝 Funcionalidades de tarefas"
  
- name: "area:matrix"
  color: "ff6b6b"
  description: "📊 Matriz de Eisenhower"
  
- name: "area:notifications"
  color: "f39c12"
  description: "🔔 Sistema de notificações"
  
- name: "area:reports"
  color: "9b59b6"
  description: "📈 Relatórios e analytics"
  
- name: "area:mobile"
  color: "2ecc71"
  description: "📱 Responsividade mobile"
  
- name: "area:pwa"
  color: "3498db"
  description: "📲 Progressive Web App"

# === DEPENDÊNCIAS ===
- name: "dependencies"
  color: "0366d6"
  description: "📦 Atualizações de dependências"
  
- name: "breaking-change"
  color: "b60205"
  description: "💥 Mudança que quebra compatibilidade"
  
- name: "backwards-compatible"
  color: "0e8a16"
  description: "✅ Compatível com versões anteriores"

# === AUTOMAÇÃO ===
- name: "automated"
  color: "ededed"
  description: "🤖 Criado/atualizado automaticamente"
  
- name: "dependabot"
  color: "0366d6"
  description: "🤖 Atualização automática do Dependabot"
  
- name: "github-actions"
  color: "000000"
  description: "⚡ Relacionado ao GitHub Actions"
  
- name: "ci/cd"
  color: "28a745"
  description: "🔄 Integração/Deploy contínuo"

# === RELEASES ===
- name: "release:major"
  color: "b60205"
  description: "🚀 Release major (v1.0.0, v2.0.0)"
  
- name: "release:minor"
  color: "0075ca"
  description: "✨ Release minor (v1.1.0, v1.2.0)"
  
- name: "release:patch"
  color: "0e8a16"
  description: "🔧 Release patch (v1.0.1, v1.0.2)"
  
- name: "release:prerelease"
  color: "fbca04"
  description: "🧪 Pre-release (alpha, beta, rc)"

# === ESPECIAIS ===
- name: "good first issue"
  color: "7057ff"
  description: "👋 Boa primeira contribuição"
  
- name: "help wanted"
  color: "008672"
  description: "🙋 Ajuda externa bem-vinda"
  
- name: "question"
  color: "d876e3"
  description: "❓ Pergunta ou discussão"
  
- name: "invalid"
  color: "e4e669"
  description: "❌ Issue inválida ou mal formatada"
  
- name: "wontfix"
  color: "ffffff"
  description: "❌ Não será implementado"
  
- name: "epic"
  color: "3e4b9e"
  description: "🎯 Epic - Conjunto de funcionalidades relacionadas"
  
- name: "spike"
  color: "f39c12"
  description: "🔬 Investigação técnica"
  
- name: "hotfix"
  color: "b60205"
  description: "🚨 Correção urgente em produção"

# === PLATAFORMAS ===
- name: "platform:web"
  color: "1f77b4"
  description: "🌐 Navegador web"
  
- name: "platform:mobile"
  color: "ff7f0e"
  description: "📱 Dispositivos móveis"
  
- name: "platform:desktop"
  color: "2ca02c"
  description: "🖥️ Desktop/PWA"
  
- name: "platform:all"
  color: "9467bd"
  description: "🌍 Todas as plataformas"

# === FERRAMENTAS ===
- name: "tool:vite"
  color: "646cff"
  description: "⚡ Relacionado ao Vite"
  
- name: "tool:supabase"
  color: "3ecf8e"
  description: "🗄️ Relacionado ao Supabase"
  
- name: "tool:tailwind"
  color: "06b6d4"
  description: "🎨 Relacionado ao Tailwind CSS"
  
- name: "tool:typescript"
  color: "3178c6"
  description: "📘 Relacionado ao TypeScript"
  
- name: "tool:react"
  color: "61dafb"
  description: "⚛️ Relacionado ao React"
  
- name: "tool:eslint"
  color: "4b32c3"
  description: "🔍 Relacionado ao ESLint"
  
- name: "tool:vitest"
  color: "6e9f18"
  description: "🧪 Relacionado ao Vitest"

# === MAINTENANCE ===
- name: "maintenance"
  color: "fbca04"
  description: "🔧 Manutenção geral do projeto"
  
- name: "cleanup"
  color: "ededed"
  description: "🧹 Limpeza de código"
  
- name: "debt"
  color: "d93f0b"
  description: "💳 Débito técnico"
  
- name: "optimization"
  color: "0e8a16"
  description: "⚡ Otimização de código"