name: 💡 Feature Request
description: Sugira uma nova funcionalidade para o projeto
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade! Por favor, preencha as informações abaixo para nos ajudar a entender sua proposta.

  - type: textarea
    id: problem
    attributes:
      label: Problema Relacionado
      description: Existe um problema relacionado a esta feature? Por favor, descreva.
      placeholder: "Estou sempre frustrado quando..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Descreva a solução que você gostaria de ver.
      placeholder: "Eu gostaria que..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Descreva quaisquer soluções ou funcionalidades alternativas que você considerou.
      placeholder: "Outras opções que considerei..."

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Qual você considera ser a prioridade desta funcionalidade?
      options:
        - Baixa
        - Média
        - Alta
        - Crítica
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexidade Estimada
      description: Qual você acredita ser a complexidade de implementação?
      options:
        - Simples
        - Média
        - Complexa
        - Não sei
    validations:
      required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: Tipo de Funcionalidade
      description: Que tipo de funcionalidade é esta?
      options:
        - label: Interface do usuário
        - label: Funcionalidade de backend
        - label: Integração com serviços externos
        - label: Performance
        - label: Segurança
        - label: Acessibilidade
        - label: Documentação
        - label: Outro

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: Se você tem mockups, wireframes ou screenshots que ajudem a explicar a funcionalidade, adicione aqui.
      placeholder: Cole suas imagens aqui...

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Adicione qualquer outro contexto, links ou informações sobre a feature request aqui.
      placeholder: Qualquer informação adicional...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Por favor, confirme que você:
      options:
        - label: Procurei por feature requests similares antes de criar esta
          required: true
        - label: Esta funcionalidade se alinha com os objetivos do projeto
          required: true
        - label: Li o guia de contribuição
          required: true
        - label: Estou disposto(a) a ajudar na implementação se necessário
          required: false