
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usar variáveis de ambiente para maior segurança
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Verificar se as variáveis de ambiente estão definidas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Erro: Variáveis de ambiente do Supabase não definidas. Verifique o arquivo .env');
}

// Configurações de segurança para o cliente Supabase
const supabaseOptions = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: localStorage,
    storageKey: 'sb-xusvqzlusdxirznsyrzo-auth-token',
  },
  global: {
    // Configurações globais para aumentar segurança nas requisições
    headers: {
      'X-Client-Info': 'eisenhower-task-manager',
    },
  },
  // Limite de tempo de requisição para evitar ataques de exaustão
  realtime: {
    timeout: 30000, // 30 segundos
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  supabaseOptions
);

// Função auxiliar para limpar completamente o armazenamento do Supabase
export const clearSupabaseStorage = () => {
  try {
    // Forçar logout do Supabase
    supabase.auth.signOut({ scope: 'global' })
      .then(() => console.log('Supabase signout executado'))
      .catch(e => console.error('Erro ao executar signout do Supabase:', e));
    
    // Remover token específico do Supabase
    localStorage.removeItem('sb-xusvqzlusdxirznsyrzo-auth-token');
    sessionStorage.removeItem('sb-xusvqzlusdxirznsyrzo-auth-token');
    
    // Remover as credenciais personalizadas
    localStorage.removeItem('supabaseUrl');
    localStorage.removeItem('supabaseKey');
    
    // Remover outros tokens possíveis - abordagem mais agressiva
    const allLocalStorageKeys = Object.keys(localStorage);
    const allSessionStorageKeys = Object.keys(sessionStorage);
    
    // Limpar TODOS os tokens que possam estar relacionados ao Supabase
    allLocalStorageKeys.forEach(key => {
      if (key.includes('supabase') || 
          key.startsWith('sb-') || 
          key.includes('auth') ||
          key.includes('token') ||
          key.includes('session')) {
        console.log('Removendo do localStorage:', key);
        localStorage.removeItem(key);
      }
    });
    
    allSessionStorageKeys.forEach(key => {
      if (key.includes('supabase') || 
          key.startsWith('sb-') || 
          key.includes('auth') ||
          key.includes('token') ||
          key.includes('session')) {
        console.log('Removendo do sessionStorage:', key);
        sessionStorage.removeItem(key);
      }
    });
    
    // Limpar quaisquer dados relacionados com autenticação
    localStorage.removeItem('gotrue.user');
    sessionStorage.removeItem('gotrue.user');
    
    console.log('Limpeza do armazenamento do Supabase concluída');
    return true;
  } catch (error) {
    console.error('Erro ao limpar armazenamento do Supabase:', error);
    return false;
  }
};

// Verificar se o cliente Supabase está conectado
export const isSupabaseConnected = () => {
  try {
    return Boolean(
      (localStorage.getItem('supabaseUrl') && localStorage.getItem('supabaseKey')) || 
      (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
    );
  } catch (error) {
    console.error('Erro ao verificar conexão do Supabase:', error);
    return false;
  }
};
