// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnrfhzaevhzynqufwaqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucmZoemFldmh6eW5xdWZ3YXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNTY1MDAsImV4cCI6MjA4MzgzMjUwMH0.CjE7D3y4LmnHAwi9QBLXx2q75Q6qOywK5g3bObYC2ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});